version: "3.8"

services:

  postgres-dw:
    image: postgres:13
    container_name: shopzada_postgres
    environment:
      POSTGRES_DB: shopzada_dw
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      - ./dataset:/dataset

  airflow-init:
    build: .
    container_name: airflow_init
    entrypoint: >
      bash -c "airflow db migrate && airflow users create --username admin --firstname Admin --lastname User --role Admin --password admin --email admin@example.com"

      
    depends_on:
      - postgres-dw

  airflow-webserver:
    build: .
    container_name: shopzada_airflow_web
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:user@postgres-dw:5432/shopzada_dw
      AIRFLOW__CORE__FERNET_KEY: "AIRU_04bNan25Lf5wYSXc-mwGt_Nqe7-tNqTp_zY4lk="
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /opt/airflow:/opt/airflow/scripts
      DB_HOST: postgres-dw
      DB_NAME: shopzada_dw
      DB_USER: admin
      DB_PASS: user
      DB_PORT: 5432
    depends_on:
      - postgres-dw
      - airflow-init
    volumes:
      - ./logs:/opt/airflow/logs
      - ./dataset:/opt/airflow/dataset
      - ./workflows:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    build: .
    container_name: shopzada_airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:user@postgres-dw:5432/shopzada_dw
      AIRFLOW__CORE__FERNET_KEY: "AIRU_04bNan25Lf5wYSXc-mwGt_Nqe7-tNqTp_zY4lk="
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /opt/airflow:/opt/airflow/scripts
      DB_HOST: postgres-dw
      DB_NAME: shopzada_dw
      DB_USER: admin
      DB_PASS: user
      DB_PORT: 5432
    depends_on:
      - postgres-dw
      - airflow-init
    volumes:
      - ./logs:/opt/airflow/logs
      - ./dataset:/opt/airflow/dataset
      - ./workflows:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    command: airflow scheduler

volumes:
  postgres_data:
