version: "3.8"

services:
  postgres-dw:
    image: postgres:13
    container_name: shopzada_postgres
    environment:
      POSTGRES_DB: shopzada_dw
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      - ./dataset:/dataset

  etl-worker:
    build: .
    container_name: shopzada_etl
    volumes:
      - ./dataset:/app/dataset
      - ./scripts:/app/scripts
    environment:
      DB_HOST: postgres-dw
      DB_PORT: 5432
      DB_NAME: shopzada_dw
      DB_USER: admin
      DB_PASS: user
    depends_on:
      - postgres-dw
    command: ["sleep", "infinity"]

volumes:
  postgres_data:
